### ISSUE TITLE
BT does not post Pixiv images in select channels with no apparent cause

### ISSUE THREAD

**Issue by Syampuuh** [VTGare/boe-tea-go#9] opened 2021-05-18 15:40 UTC
I recently created a set of new channels in a server of mine; BT does not respond to any Pixiv links in these new channels, but does post Twitter images and respond to other commands within them. Pixiv images are also posted without issue in the earlier existing channels. The bot role has administrative privileges, so I don't think this is a permissions issue. I've tried kicking and re-inviting the bot, as well as disabling and then reenabling Pixiv posting, but neither has made any change.

I tried using the "add channel" command, but it only returns an error.
![image](https://user-images.githubusercontent.com/25516124/118681546-48a2c800-b7c5-11eb-98e8-2c36d644a111.png)

If it helps any, the server ID is 521133219916283929, and here is the current configuration.
![1621352247](https://user-images.githubusercontent.com/25516124/118681256-0e392b00-b7c5-11eb-9199-398e78df6612.png)

**Comment by VTGare** [comment] 2021-05-22 11:45
> I tried using the "add channel" command, but it only returns an error.

There was a data error on the database, I already fixed it. The command should work now.

> I recently created a set of new channels in a server of mine; BT does not respond to any Pixiv links in these new channels, but does post Twitter images and respond to other commands within them.

This however is really weird. I couldn't reproduce this error neither locally, nor in production.

**Comment by VTGare** [comment] 2021-06-13 11:38
The problem was that NSFW artworks were skipped in SFW channels without any feedback. Closing the issue.

**Closed by VTGare** 2021-06-13 11:38 UTC
